on:
  push:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Tar action step
        uses: ./ # Uses an action in the root directory
        id: justTar
        with:
          command: c
          cwd: ./test
          files: |
            ./toCompress
          outPath: yolo.tar
      - name: Get the output (tar)
        run: echo "The output was ${{ steps.justTar.outputs.done }} with ${{ steps.justTar.outputs.tarName }}"
      - name: Compress action step
        uses: ./ # Uses an action in the root directory
        id: tarGz
        with:
          command: z
          cwd: ./test
          files: |
            ./toCompress
          outPath: yolo.tar.gz
      - name: Get the output (targz)
        run: echo "The output was ${{ steps.justTar.outputs.done }} with ${{ steps.tarGz.outputs.tarName }}"
          # Use the output from the `compress` step
      - uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: yolo.tar*
